### ISSUE TITLE
Can't install on Firefox for Android

### ISSUE THREAD

**Issue by JeelsBoobz** [dessant/buster#252]
**System**

* OS name: Android
* OS version: 10
* Browser name: Firefox Nightly
* Browser version: Nightly 201107 17:01 (84)

**Extension**

* Extension version: 1.1.0

* User input simulation: [e.g. yes, no]

* Client app version: [e.g. 1.0.0]
* Client app installed successfully: [e.g. yes, no]

**Bug description**
I can't install it. Already add to my collections
![Screenshot_20201108-135320](https://user-images.githubusercontent.com/38210868/98459089-d031cd80-21c9-11eb-93c5-026534ccfb50.jpg)

**Logs**

Browser:
```
// REPLACE WITH LOGS
```

Client app:
```
// REPLACE WITH LOGS
```

**Comment by dessant** [comment]
Firefox for Android is currently not supported due to an upstream regression: https://github.com/mozilla-mobile/fenix/issues/15904

**Comment by JeelsBoobz** [comment]
Will be possible to install for next update?

**Comment by dessant** [comment]
It entirely depends on when the bug in Firefox is fixed, you could ask them.

**Comment by JeelsBoobz** [comment]
But i can install this addons on Firefox Android version 68

**Comment by dessant** [comment]
See the bug report I've linked in the first comment, they've introduced the bug in Fenix, the classic Firefox for Android does not have this issue.

**Comment by Aequita** [comment]
Silly question - should it work on the latest Firefox release (83.1.0) for android?
If so - how is it possible to add Buster? I only see "Recommended" Add-ons?

**Comment by JeelsBoobz** [comment]
> Silly question - should it work on the latest Firefox release (83.1.0) for android?
> If so - how is it possible to add Buster? I only see "Recommended" Add-ons?

Firefox Nightly

**Comment by Aequita** [comment]
Sorry if I have to ask again for clarification, but ...
A) The Buster addon worked for mobile Firefox with past and current versions, but does not work with the nightly build anymore?
B) The current nightly is to be the first version it should ever work?

Incase A): How can it be installed?

**Comment by JeelsBoobz** [comment]
> Sorry if I have to ask again for clarification, but ...
> A) The Buster addon worked for mobile Firefox with past and current versions, but does not work with the nightly build anymore?
> B) The current nightly is to be the first version it should ever work?
> 
> Incase A): How can it be installed?

I'am asking this questions

**Comment by bingoxo** [comment]
@Aequita @JeelsBoobz Firefox stopped allowing extensions in their android app so now you can only install one of the 9 recommended ones , to install any  extension from addons page you have to have the nightly version and do this : https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/
with current version of firefox nightly buster doesn't work anymore (hence this issue)

so far the only way to  get buster working on mobile is use another browser that has extensions support and afaik there is only one other one : kiwi browser  , hopefully firefox will fix their stuff soon and we wont need to install other browsers

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
**System**
<

* OS name: Android
* OS version: 10
* Browser name:  Firefox Mobile nightly
* Browser version: 88

**Extension**


* Extension version: 1.1.0

* User input simulation: [e.g. yes, no]

* Client app version: [e.g. 1.0.0]
* Client app installed successfully: [e.g. yes, no]

**Bug description**

Buster can't be added installed to Firefox Mobile, but chromium mobile forks like kiwi browser.

Screenshots:
![IMG_20210320_022636.jpg](https://user-images.githubusercontent.com/46166740/111855284-f0ae2900-891b-11eb-9408-da133eff7970.jpg)![IMG_20210320_022703.jpg](https://user-images.githubusercontent.com/46166740/111855286-f277ec80-891b-11eb-98ed-950c23779832.jpg)

**expected behavior**

![IMG_20210320_023349.jpg](https://user-images.githubusercontent.com/46166740/111855375-70d48e80-891c-11eb-8dcd-a266039716a9.jpg)

**Comment by tdee912** [comment]
this extension supports firefox android version **68.11.0**, tks dude!

![firefox 68 11 0](https://user-images.githubusercontent.com/9406349/127555684-82d190c9-10dd-4819-aaf5-e676ff55cac5.jpeg)

**Comment by vjrmy** [comment]
What do you think about it? @dessant 
https://github.com/mozilla-mobile/fenix/issues/22716#issuecomment-1026816217

**Comment by dessant** [comment]
The upstream bug appears to have been fixed, but I don't recommend using the extension on Android, because the client app cannot be installed on that platform.

https://github.com/dessant/buster/wiki/Inaccessible-reCAPTCHA-audio-challenge

**Comment by vjrmy** [comment]
> The upstream bug appears to have been fixed, but I don't recommend using the extension on Android, because the client app cannot be installed on that platform.
> 
> https://github.com/dessant/buster/wiki/Inaccessible-reCAPTCHA-audio-challenge

which update version do you mean? because I have tried firefox nightly version 104.0a1 still can't install addon buster

**Comment by dessant** [comment]
It looks like the upstream issue was closed without QA testing, I've just checked and both LastPass and Buster fail to install.

https://github.com/mozilla-mobile/fenix/issues/15904

**Comment by henosch** [comment]
> Buster can't be added installed to Firefox Mobile, but chromium mobile forks like kiwi browser.

You can add to kiwi browser, but isn't working.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
yes henosch, Can confirm it no longer works.

**Comment by WalterBishop69** [comment]
Yeah I second the fact that when you install it on kiwibrowser next which if you don't know is distinctly different from kiwi browser in that it is frequently updated following current versions of chromium by Dev and should and for the most part runs almost all extensions that the desktop version of Chrome vivaldy and edge as well as many other's desktop browsers can run. It only has problems when there is no gui that pops up on the page when you click the addon from the toolbar. It's OK to go to a seperate page for settings but alot of times it needs a popup overlay on same page or for some reason the input doesn't transfer back to the page you are trying to change or effect with the addon. So this small change be it a one click button or smaller version of te current window your using oerlayed on top  should get it working on kiwi if made to your Chrome extension because like stated above it loads and you can do the input on your current system it just doesn't actually effect the page you're trying to work on then you could say it's supported on Android. And if you are familiar with the Firefox or old Kiwi extension setup I understand your standoffishness towards supporting a half @$$ed implementation but you next is on a whole nother level he just about got it right where it works perfect without having to do any kind of janky workaround so it's worth looking into I think just for the fact that you can stick that Android sticker on your supported list with very minimal effort
